configmap:
  logstashConf: |-
    # all input will come from filebeat, no local logs
     input{
       beats {
         port => 5044
         }
         }
     output {}
  logstashYml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
deployment:
  logstash:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsUser: 0
    image:
      repository: opensearchproject/logstash-oss-with-opensearch-output-plugin
      tag: latest
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 5044
    protocol: TCP
    targetPort: 5044
  type: ClusterIP
