apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash-sa-pvc.fullname" . }}-logstash-configmap
  labels:
  {{- include "logstash-sa-pvc.labels" . | nindent 4 }}
data:
  logstash.conf: {{ .Values.logstashConfigmap.logstashConf | toYaml | indent 1 }}
  logstash.yml: {{ .Values.logstashConfigmap.logstashYml | toYaml | indent 1 }}