apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash-helm.fullname" . }}-configmap
  labels:
  {{- include "logstash-helm.labels" . | nindent 4 }}
data:
  logstash.conf: {{ .Values.configmap.logstashConf | toYaml | indent 1 }}
  logstash.yml: {{ .Values.configmap.logstashYml | toYaml | indent 1 }}