apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-opensearch.fullname" . }}-mysql
  labels:
  {{- include "mysql-opensearch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: mysql
    {{- include "mysql-opensearch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mysql
      {{- include "mysql-opensearch.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ quote .Values.mysql.mysql.env.mysqlRootPassword }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mysql.mysql.image.repository }}:{{ .Values.mysql.mysql.image.tag
          | default .Chart.AppVersion }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}